//MANAGER
  //TEACHER, SCOREBOARD SLOT INTO THIS
class Board {
  //PASS TEACHER SOP IT CAN TELL IT WHAT TO DO 
  //PASS SCOREBOARD AS A PUNCH CARD, TO KEEP TRACK OF TERMINOLOGY
  
  
  //4 || 8 AMOUNT OF TARGET DECIDED BY TEACHER
  
  //BOARD KNOWS ABOUT TEACHER AND SCOREBOARD
}
