//FACTORY
class Teacher {
  //METHOD 
    //GET NOTES
    //GET NEXT RYTHM, RETURNS NEXT RYHTM 

  
  //RECORD FOR LEARNING
    //TEACHER NEEDS TO BE TOLD ABOUT NOTEs
      // IE IF IT WAS INEFFECTIVE OR EFFECITVE
      // 

}
